# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2008-2011 Kristian Høgsberg
# SPDX-FileCopyrightText: 2010-2011 Intel Corporation
# SPDX-FileCopyrightText: 2012-2013 Collabora, Ltd.
# SPDX-FileCopyrightText: 2015 Sebastian Kügler <sebas@kde.org>
#
# SPDX-License-Identifier: MIT-CMU

from .org_kde_kwin_outputdevice import OrgKdeKwinOutputdevice  # noqa: F401
