# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2015 Martin Gräßlin
#
# SPDX-License-Identifier: LGPL-2.1-or-later

from .org_kde_kwin_dpms import OrgKdeKwinDpms  # noqa: F401
from .org_kde_kwin_dpms_manager import OrgKdeKwinDpmsManager  # noqa: F401
